version: '2.4'

services:

  tor:
    build: ./tor/build
    container_name: tor_build
    restart: always
    ports:
      - 127.0.0.1:8050:9050
      - 127.0.0.1:8051:9051
      - 127.0.0.1:8118:8118
    expose:
      - 9050
      - 9051
      - 8118
    volumes:
      - ./tor/etc:/etc/tor
    #   # chown -R root ./tor/lib
      - ./tor/lib:/var/lib/tor
    networks:
      tor:
        ipv4_address: 10.6.0.50
      torext:
      
  bitcoind:
    build: ./bitcoin
    stop_grace_period: 5m
     #command: echo "Bitcoin disabled"
    restart: always
     #stop_grace_period : 1m30s
     #stop_signal : SIGINT
    depends_on: 
      - tor
    container_name: bitcoin_build
    expose: 
      - 8332
      - 8333
      - 28332
    ports:
      - 8333:8333
    volumes:
      - ./bitcoin/bitcoin:/bitcoin
      - ./tor/lib:/var/lib/tor
    networks:
      bitcoinint:
        ipv4_address: 10.19.0.10
      tor:
        ipv4_address: 10.6.0.51
      bitcoin:
      
networks:
  tor:
    internal: true
    ipam:
      config:
        - subnet: 10.6.0.0/16
      
  torext:
    ipam:
      config:
        - subnet: 10.9.0.0/16

  bitcoinint:
    ipam: 
      config:
         - subnet: 10.19.0.0/16
    internal: true 
  bitcoin:
    external: true


