version: '2.4'

services:

  tor:
    build: ./tor/build
    container_name: tor_build
    restart: always
    ports:
      - 127.0.0.1:8050:9050
      - 127.0.0.1:8051:9051
      - 127.0.0.1:8118:8118
    expose:
      - 9050
      - 9051
      - 8118
    volumes:
      - ./tor/etc:/etc/tor
    #   # chown -R root ./tor/lib
      - ./tor/lib:/var/lib/tor
    networks:
      tor:
        ipv4_address: 10.6.0.10
      torext:
      
  bitcoind:
    build: ./bitcoin
    stop_grace_period: 5m
     #command: echo "Bitcoin disabled"
    restart: always
     #stop_grace_period : 1m30s
     #stop_signal : SIGINT
    depends_on: 
      - tor
    container_name: bitcoin_build
    expose: 
      - 8332
      - 8333
      - 28332
    ports:
      - 8333:8333
    volumes:
      - ./bitcoin/bitcoin:/bitcoin
      - ./tor/lib:/var/lib/tor
    networks:
      bitcoinint:
        ipv4_address: 10.19.0.10
      tor:
        ipv4_address: 10.6.0.51
      bitcoin:
 
  lnd:    
    build: ./lnd
    container_name: lnd_build
    stop_grace_period: 5m
    depends_on:
      - bitcoind
      - tor 
    restart: always 
    volumes:
      - ./lnd/lnd:/lnd
      - ./lnd/backup:/backup
      - ./tor/lib:/var/lib/tor
    networks:
      - bitcoinint
      - bitcoin
      - tor
    ports:
      - 9911:9911
      - 9735:9735
      - 10009:10009
      - 8080:8080
    expose:
      - 8080

  rtl: 
    container_name: rtl_build
    image: shahanafarooqui/rtl:0.11.2
    restart: unless-stopped 
    depends_on: 
      - lnd
      - bitcoind
    volumes: 
      - ./rtl/RTL-Config.json:/RTL/RTL-Config.json
      - ./lnd/lnd:/shared:ro 
      - ./lnd/backup:/backup
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      PORT: 3000
  #    HOST: rtl
      MACAROON_PATH: /shared/data/chain/bitcoin/mainnet
      LN_SERVER_URL: https://lnd:8080
      CONFIG_PATH: ''
      LN_IMPLEMENTATION: LND 
      SWAP_SERVER_URL: https://lnd:8080
      SWAP_MACROON_PATH:  /shared/data/chain/bitcoin/mainnet 
      RTL_SSO: 0
      RTL_COOKIE_PATH: ''
      LOGOUT_REDIRECT_LINK: ''
      RTL_CONFIG_PATH: /RTL
      BITCOIND_CONFIG_PATH: ''
      CHANNEL_BACKUP_PATH: /backup
    networks:
        bitcoinint: 
        bitcoin:
        tor:   
             ipv4_address: 10.6.0.12

  electrs: 
    container_name: electrs_build 
    image: iangregsondev/electrs
    restart: unless-stopped
    depends_on: 
      - tor
      - bitcoind
#      - lnd  
    volumes:
      - ./electrs:/root
      - ./bitcoin/bitcoin:/root/.bitcoin
#      - ./tor/lib:/var/lib/tor
      - ./electrs/electrs.toml:/etc/electrs/config.toml
#      - ./electrs/build/electrs:/build/electrs
#      - ./electrs/build/bitcoin:/build/bitcoin
#      - ./electrs/build/:/build 
    ports:
      - 50001:50001
#      - 4224:4224
    expose: 
      - 50001
    networks:
       bitcoinint:
       bitcoin:
       tor:
            ipv4_address: 10.6.0.11

  specter:
    build: ./specter
    container_name: specter-desktop
#    image: lncm/specter-desktop:v1.7.0 
    depends_on: 
      - bitcoind
#    network_mode: host
    ports:
      - 25441:25441
    expose:
      - 25441
    restart: on-failure
    stop_grace_period: 5m30s
    environment:
      BTC_RPC_USER: pratap
      BTC_RPC_PASSWORD: India@2019
      BTC_RPC_HOST: 10.19.0.10
      BTC_RPC_PORT: 8332
      BTC_RPC_PROTOCOL: http
##      BTC_RPC_PROTOCOL: tcp
    privileged: true
    volumes:
       - ./bitcoin/bitcoin:/data/.bitcoin
       - ./specter:/data/.specter
#       - /dev:/dev
#       - /etc/udev:/etc/udev 
    networks:
      bitcoinint:
      bitcoin:

  oniondb:
    image: mariadb
    container_name: oniondb_build
    networks:
      - db
    volumes: 
      - ./oniondb:/var/lib/mysql
    restart: always
    expose: 
      - 3306
    environment:
      MYSQL_DATABASE: onionweb
      MYSQL_USER: onionweb
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
 
  onionweb: #address.onion
    image: wordpress
    restart: always
    depends_on:
      - oniondb
      - tor 
    expose:
      - 80
    environment:
      admin: admin:pratap
      WORDPRESS_DB_NAME: onionweb 
      WORDPRESS_DB_HOST: oniondb:3306
      WORDPRESS_DB_USER: onionweb
      WORDPRESS_DB_PASSWORD: test
      http_proxy: http://tor:8118
      https_proxy: http://tor:8118
      HTTP_PROXY: http://tor:8118
      HTTPS_PROXY: http://tor:8118
    volumes:
      - ./onionweb:/var/www/html
    networks:
      tor: 
          ipv4_address: 10.6.0.13
      db:

 
  lightningd:
    build: ./lightning 
    container_name: lightningd_build
    stop_grace_period: 5m
    depends_on:
      - bitcoind
      - tor 
    expose:
      - 9732
    #rest plugin 
      - 3002
      - 4001
    ports: 
      - 9732:9732
  # rest plugin 
#      - 127.0.0.0.1:3002:3002
#      - 127.0.0.0.1:4001:4001
      - 3002:3002
      - 4001:4001
    restart: always 
    volumes:
      - ./lightning/lightning:/root/.lightning
      - ./tor/lib:/var/lib/tor
      - ./bitcoin/bitcoin:/root/.bitcoin
      - ./lightning/certs:/usr/local/c-lightning-REST/certs
    networks:
      bitcoinint:
         ipv4_address: 10.19.0.15
      bitcoin: 
      tor:
          ipv4_address: 10.6.0.14
#      torext:
   # ports:
    #  - 9911:9911
    #  - 9735:9735
    #  - 10009:10009
    #  - 8080:8080
    #expose:
    #  - 8080
    
#  lightningrd:
#    image: saubyk/c-lightning-rest
#    container_name: lightningr_build
#    stop_grace_period: 5m
#    depends_on:
#      - lightningd
#    expose:
#      - 3002
#      - 4001
#    restart: always 
#    volumes:
#    networks:
  
networks:
  tor:
    internal: true
    ipam:
      config:
        - subnet: 10.6.0.0/16
      
  torext:
    ipam:
      config:
        - subnet: 10.9.0.0/16

  bitcoinint:
    ipam: 
      config:
         - subnet: 10.19.0.0/16
    internal: true 
  bitcoin:
    external: true
  db:
    internal: true 
    ipam: 
      config: 
        - subnet: 10.11.0.0/16
